version: "3"
services:
  ngdns-frontend-{version}:
    environment:
    - MQTT_HOST=192.168.22.26
    - MQTT_PORT=1883
    #healthcheck:
      #test: ["/bin/sh", "curl","-X","GET", "-f", "http://127.0.0.1:8080/actuator/health"]
      #interval: 1m30s
      #timeout: 10s
      #retries: 3
    build:
      context: .
      dockerfile: ../Dockerfile
    image: 192.168.233.1:5000/ngdns-frontend:{version}
    networks:
      dev:
        aliases:
         - ngdns-frontend-{version}
networks:
  dev:
    external:
      name: dev
